---
title: "Tidy Tuesday 2021-09-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidytuesdayR)
library(tidyverse)

(tt_output <- tt_load_gh("2021-09-21"))
```

```{r}
tt <- tt_download(tt_output, "nominees.csv")
nominees <- tt$nominees

skimr::skim(nominees)
```
Explore

```{r}
nominees %>%
  distinct(type)

nominees %>%
  mutate(
    year = as.numeric(str_extract_all(category, "(\\d{4})$", simplify = TRUE)),
    category = str_remove_all(category, " - (\\d{4})$")
  ) %>%
  add_count(category, sort = TRUE) %>%
  filter(
    str_detect(category, "Outstanding Comedy Series"),
    type == "Winner"
  ) %>%
  select(category, year, title) %>%
  distinct()

nominees %>%
  separate(col = production, into = c("name", "job"), sep = ",") %>%
  count(job, title, sort = TRUE)

nominees %>%
  count(title, sort = TRUE)
```

Now I know what I want to do. Animate a plot over time - count of award winners
by network.

```{r}
(dist_year <-
  nominees %>%
  filter(type == "Winner") %>%
  mutate(
    year = as.numeric(str_extract_all(category, "(\\d{4})$", simplify = TRUE))
  ) %>%
  count(year, distributor, name = "value") %>%
  group_by(year) %>%
  mutate(
    rank = floor(rank(-value, ties.method = "first")),
  ) %>%
    filter(rank < 11) %>%
    ungroup()
)
```

Create the plot

```{r message=FALSE, warning=FALSE, paged.print=FALSE}
library(gganimate)

p <-
  dist_year %>%
  filter(
    year %in% seq(2001, 2021, by = 1)
    #year == 2021
  ) %>%
  ggplot(aes(rank, group = distributor, fill = as.factor(distributor), color = as.factor(distributor))) +
  geom_tile(aes(
    y = value / 2,
    height = value,
    width = 0.9
  ), alpha = 0.8, color = NA) +
  geom_text(aes(y = 0, label = paste(distributor, " ")), vjust = 0.2, hjust = 1) +
  geom_text(aes(y = value, label = value, hjust = -0.5)) +
  coord_flip(clip = "off", expand = FALSE) +
  theme(
    axis.line = element_blank(),
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    legend.position = "none",
    panel.background = element_blank(),
    panel.border = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.grid.major.x = element_line(size = .1, color = "grey"),
    panel.grid.minor.x = element_line(size = .1, color = "grey"),
    plot.title = element_text(size = 25, hjust = 0.5, face = "bold", colour = "grey"),
    plot.subtitle = element_text(size = 18, hjust = 0.5, face = "italic", color = "grey"),
    plot.caption = element_text(size = 8, hjust = 0.5, face = "italic", color = "grey"),
    plot.background = element_blank(),
    plot.margin = margin(2, 2, 2, 4, "cm")
  ) +
  scale_y_continuous(labels = scales::comma) +
  scale_x_reverse()

anim <- p +
  transition_states(year, transition_length = 4, state_length = 1) +
  labs(
    title = "Emmy Award Year : {closest_state}",
    subtitle = "Count of Award Winners by Network",
    caption = "Source: #tidytuesday 2021-09-21"
  ) +
  view_follow(fixed_x = TRUE)
```


```{r}
animate(plot = anim, nframes = 400, fps = 20,  width = 600, height = 500, 
        renderer = gifski_renderer("gganim.gif"))
```





